### ISSUE TITLE
XLFileLogger - Consider adding auto-rolling/max size/max files to keep

### ISSUE THREAD

**Issue by gcox** [swisspol/XLFacility#10]
It would be helpful, for me at least, if the file logger supported auto-rolling new messages into a new file based on a max file size.  I'd prefer to just provide it with a directory path, maybe a file name format to use for each file, a max file size, and a max number of files to keep around.

**Comment by swisspol** [comment]
That's an interesting approach. The `XLTCPServerLogger` class is also using another logger internally, so it wouldn't be a new concept. Looks good to me!

You would need to pay attention to concurrency and locking of course e.g. if you need to roll the logger in the middle of 2 log calls.
