### ISSUE TITLE
Enhancement request - exposing Macros to Swift

### ISSUE THREAD

**Issue by nickvelloff** [swisspol/XLFacility#11]
Hello again!

Just want to request the exposure of the macros (or re-implementation) to Swift to reduce the unneeded code clutter. 

I attempted the below type of approach from SO but there is a bit of complexity in the macros i'm not familiar with. If they could be "wrapped" instead of re-implementing then a single code base could be maintained. 

Anyway though I would ask. Either way enjoying the lib so thanks for sharing it.

http://stackoverflow.com/questions/24133695/how-to-use-objective-c-code-with-define-macros-in-swift

.h file:
# define AD_SIZE CGSizeMake(320, 50)
- (CGSize)adSize;
  .m file:
- (CGSize)adSize { return AD_SIZE; }
  And in Swift:

Since this is a class method you can now use it almost as you would the #define. If you change your #define macro - it will be reflected in the new method you created In Swift:

let size = YourClass.adSize()What I did is to create a class method that returns the #define.

Example:

.h file:
# define AD_SIZE CGSizeMake(320, 50)
- (CGSize)adSize;
  .m file:
- (CGSize)adSize { return AD_SIZE; }
  And in Swift:

Since this is a class method you can now use it almost as you would the #define. If you change your #define macro - it will be reflected in the new method you created In Swift:

let size = YourClass.adSize()

**Comment by swisspol** [comment]
I see where you're going but the problem here is that the macros are needed for performance and do as many things as possible at the call site versus inside XLFacility.

What about `static inline` functions in a header? Do they work in Swift? Assuming the compiler does inline, that would be equivalent to the macros AFAIK.

**Comment by nickvelloff** [comment]
I *may* be able to use a ```static inline``` function in a header. If you would be willing to do a quick one for me I would be happy to attempt to bridge and access it in swift.

This is what Apple has to say about it (https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithCAPIs.html):

>Complex Macros

>Complex macros are used in C and Objective-C but have no counterpart in Swift. Complex macros are macros that do not define constants, including parenthesized, function-like macros. You use complex macros in C and Objective-C to avoid type-checking constraints or to avoid retyping large amounts of boilerplate code. However, macros can make debugging and refactoring difficult. In Swift, you can use functions and generics to achieve the same results without any compromises. Therefore, the complex macros that are in C and Objective-C source files are not made available to your Swift code.

**Comment by swisspol** [comment]
You don't need to modify XLFacility for this: I suggest you try directly using `static inline` functions in a random C header from Swift and see what happens.

Also be aware that I don't code in Swift and am only superficially familiar with the language, so it's going to be a long time before I can look at this (months for sure).

**Comment by nickvelloff** [comment]
Sounds good.

What I was asking for actually was just an example of a static inline function in Obj-C so I can try to access it from Swift. Swift to my knowledge does not directly support it but may be able to access it through the “header bridge” which is how i’m using XLFacility in my Swift project.

Sorry for confusion.

**Comment by swisspol** [comment]
Ah, sure, here's an example:
```objc
static inline double MultiplyBy2(double x) {
  return 2 * x;
}
```
Throw this in a header file and try calling from Swift!

**Comment by nickvelloff** [comment]
```Swift
let x = MultiplyBy2(2)
println(x)
```

4.0 ! Works. So now what :)

**Comment by swisspol** [comment]
Do `__LINE__` and `__FILE__` preprocessor macros exist in Swift? Thinking about it, that's the other reasons while macros are needed: so that the line and file of the caller can be captured as a "logging tag". That's optional though.

**Comment by swisspol** [comment]
In any case you can try creating a `XLFacilitySwiftFunctions.h` file inspired/duplicated from `XLFacilityMacros.h` and redefining each macro as an inline function e.g.
```
#define XLOG_VERBOSE(...) do { if (XLMinLogLevel <= kXLLogLevel_Verbose) [XLSharedFacility logMessageWithTag:XLOG_TAG level:kXLLogLevel_Verbose format:__VA_ARGS__]; } while (0)
```
becomes something like
```
static inline void XLOG_VERBOSE(NSString* tag, XLLogLevel level, NSString* format, ...) {
  if (XLMinLogLevel <= 1) {
        va_list arguments;
        va_start(arguments, format);
        NSString* message = [[NSString alloc] initWithFormat:format arguments:arguments];
        va_end(arguments);
        [XLSharedFacility logMessage:message withTag:tag level:level];
  }
}
```

**Comment by nickvelloff** [comment]
They are available actually:
```swift
func assert(condition: @autoclosure () -> Bool, _ message: String = "",
	file: String = __FILE__, line: Int = __LINE__) {
		#if DEBUG
			if !condition() {
				println("assertion failed at \(file):\(line): \(message)")
				abort()
			}
		#endif
}
```

**Comment by nickvelloff** [comment]
Maybe a more relevant example:
```swift
func logAndAssert(condition: @autoclosure () -> Bool, _ message: StaticString = "",
	file: StaticString = __FILE__, line: UWord = __LINE__) {

	logMessage(message)
	assert(condition, message, file: file, line: line)
}
```

**Comment by swisspol** [comment]
But in the example, `__LINE__ ` will evaluate with the line # where `logAndAssert()` is defined or where it is called?

**Comment by nickvelloff** [comment]
__FILE__ (String): The filename of the file in which the currently executing code appears
__LINE__ (Int): The line number in the source file on which the currently executing code appears

Is this what we need?

**Comment by swisspol** [comment]
Not sure, the doc is not very clear actually. Best thing is to try!

**Comment by nickvelloff** [comment]
I certainly will give it a try. My concern is not understanding the Macro syntax fully. Maybe I can get some help with that somewhere. I'm really comfortable in Swift and moderate in Obj-C. I only really used fairly simple Macros in the past.

**Comment by swisspol** [comment]
That's OK, ignore the macros then, just see my comment at https://github.com/swisspol/XLFacility/issues/11#issuecomment-74772402.

You can implement such wrappers using static inline C functions or why not Swift functions directly? If the latter, see if you can use `__LINE__` so that it gets replaced by the line # of the callsite, instead of the line # of the actual function implementation.

**Comment by nickvelloff** [comment]
OK I see. I was concerned if using the Swift functions I might not get the performance boost you described but that might not be the case. 
I'll give it a shot. I need to try to understand the Macros to know exactly what to implement.

**Comment by pulimento** [comment]
Any news on this matter?
