### ISSUE TITLE
XLFacilityMacros.h and Swift

### ISSUE THREAD

**Issue by nickvelloff** [swisspol/XLFacility#8]
XLFacility is working properly when added to the bridging header. 

After adding XLFacilityMacros.h to the header they do not seem to be recognized. I know that Swift essentially doesn't adopt the Macros concept in the same way. 

Is there a way I can do this?

Otherwise logging will look like this:
XLFacility.sharedFacility().logMessage("oauthTokenViable true, Attempt registerUserToken", withTag: nil, level: XLLogLevel.LogLevel_Debug)

Header entries:
#import "XLFacilityMacros.h"
#import "XLFacility.h"

**Comment by nickvelloff** [comment]
By the way this library is fantastic and if it works well for Swift I'll do a medium post to let my fellow Swift developers know I recommend migrating from XCGLogger.

**Comment by swisspol** [comment]
Hummm That's a good question. I'm afraid I don't know Swift enough to offer a solution though. How do other logging solutions in Swift implement the equivalent of C macros?

**Comment by nickvelloff** [comment]
Macros just don't work unfortunately as far as I can tell. 
I'm forking and going to implement some type of wrapper and test. I'll shoot you a pull request if it works appropriately and you can decide if you want the additions

**Comment by swisspol** [comment]
Awesome, thanks much!
