### ISSUE TITLE
XLUIKitOverlayLogger appears then disappears

### ISSUE THREAD

**Issue by nickvelloff** [swisspol/XLFacility#9]
Hi. 

I'm not clear based on the documentation the correct usage of the XLUIKitOverlayLogger. It works well but I'm not sure how to get it to appear and remove as needed.

**Comment by swisspol** [comment]
The current implementation does not provide any control: it automatically shows onscreen up to `overlayDuration` seconds at soon as a message is logged. You can set properties on the logger to only show above a certain log level too.

**Comment by nickvelloff** [comment]
Cool thanks.
